[package]
name = "hut"
version = "0.5.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/hidutils"
repository = "https://github.com/hidutils/hut"
description = "The HID Usage Tables"

[features]
default = ["std"]
std = []
